spring:
  datasource:
    url: jdbc:h2:~/tzoom/db/test
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    platform: hsqldb
  h2:
    console:
    enabled: true
    path: /h2-console
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml